//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveSummaryUser
    {
        public int Id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<double> CL_Allotted { get; set; }
        public Nullable<double> CL_Balance { get; set; }
        public Nullable<double> SL_Allotted { get; set; }
        public Nullable<double> SL_Balance { get; set; }
        public Nullable<double> PL_Allotted { get; set; }
        public Nullable<double> PL_Balance { get; set; }
        public Nullable<double> ML_Allotted { get; set; }
        public Nullable<double> ML_Balance { get; set; }
        public Nullable<double> OL_Allotted { get; set; }
        public Nullable<double> OL_Balance { get; set; }
        public Nullable<double> EL_Allotted { get; set; }
        public Nullable<double> EL_Balance { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> modifiedby { get; set; }
    }
}
