//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalLeaveCount
    {
        public int Id { get; set; }
        public int LeaveTypeId { get; set; }
        public Nullable<double> Count { get; set; }
        public Nullable<double> UserId { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
    }
}
